version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: "install"
          command: npm install
      - run:
          name: "build"
          command: PATH="$(npm bin):$PATH" npm run build
      - persist_to_workspace:
          root: .
          paths: ["build"]

  deploy:
    docker:
      - image: bugfactory/aws-deploy:latest
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: "deploy to S3"
          command: |
            for product_directory in /tmp/workspace/build/*/ ; do
              product_name=$(basename $product_directory)
              for hash_directory in ${product_directory%*/}*/ ; do
                aws s3 cp "$hash_directory" \
                          "s3://$S3_BUCKET_NAME/$product_name/" \
                          --acl public-read --recursive --cache-control 'max-age=31536000'
              done
              aws s3 cp "${product_directory%*/}/index.html" \
                        "s3://$S3_BUCKET_NAME/$product_name/index.html" \
                        --acl public-read --cache-control 'public, max-age=31536000, no-cache'
            done

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          requires: []
      - deploy:
          requires: [build]
          filters:
            branches:
              only: [master]
