version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: "install"
          command: yarn install
      - run:
          name: "build"
          command: REVISION=$CIRCLE_SHA1 yarn run build
      - persist_to_workspace:
          root: .
          paths: ["build"]

  deploy:
    docker:
      - image: bugfactory/aws-deploy:latest
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: "deploy to S3"
          command: |
            aws s3 sync "/tmp/workspace/build/" \
                        "s3://$S3_BUCKET_NAME/current/" \
                        --acl public-read --delete --cache-control 'public, max-age=31536000, no-cache'
            aws s3 sync "/tmp/workspace/build/" \
                        "s3://$S3_BUCKET_NAME/$CIRCLE_SHA1/" \
                        --acl public-read --delete --cache-control 'max-age=31536000'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          requires: []
      - deploy:
          requires: [build]
          filters:
            branches:
              only: [master]
